version: "3.9"
services:
    db:
        image: postgres:13-alpine
        volumes: 
            - data:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: sqla
            POSTGRES_PASSWORD: sqla
        ports:
            - 5433:5432
volumes: 
    data: