= Working with Data via SQLAlchemy Core

:toc: auto

== Inserting

* Two `inserts` -- one through a table and another one as an independent function

[source,python]
----
ins = cookies.insert().values(
    cookie_name="chocolate chip",
    cookie_recipe_url="http://some.aweso.me/cookie/recipe.html",
    cookie_sku="CC01",
    quantity="12",
    unit_cost="0.50",
)

ins = insert(cookies).values(
    cookie_name="chocolate chip",
    cookie_recipe_url="http://some.aweso.me/cookie/recipe.html",
    cookie_sku="CC01",
    quantity="12",
    unit_cost="0.50",
)
----

* Both work the same

TIP: Same as the author, I personally prefer the second option. Looks more like
     "regular" SQL we all know and - some - love

* When one of those statements is executed, they are parsed and converted into
  valid SQL by the engine

* You can even pass the args to the `execute` command itself:

[source,python]
----
ins = cookies.insert()
result = connection.execute(
    ins,
    cookie_name='dark chocolate chip',
    cookie_recipe_url='http://some.aweso.me/cookie/recipe_dark.html',
    cookie_sku='CC02',
    quantity='1',
    unit_cost='0.75'
)
----

== Selecting

* Again, two options -- as a table attribute and as a 'free-standing' function.

* I prefer the free function, will put only that one here

[source,python]
----
from sqlalchemy import select

s = select([cookies])
rp = connection.execute(s) # This is a 'ResultProxy'
results = rp.fetchall()
----

=== `ResultProxy`

* It's a wrapper around DBAPI with some goodies such as ease data access

* For example, it allows you to access rows in a result in different ways:

[source,python]
----
row = results[0]

row[1] # By index
row.cookie_name # Column name, as attribute
row[cookies.c.cookie_name] # Column object, from the table
----

* All of those 3 methods will have the same effect - accessing row's first column
  that is `cookie_name`

* It is also an iterator

[source,python]
----
for record in result:
    do_stuff_with(record)

----

* As expected, `fetchall` is memory intensive
* `first()` returns the first row and _closes the connection_
* `fetchone()` fetches the first and _leaves the connection open for future fetches_
* `scalar()` returns a single value if the result is a single record with one column

WARNING: `fetchall()` is expensive, will load everything into memory;
         `fetchone()` is dangerous, will let the connections open;

WARNING: `scalar()` will raise an exception if the result has more
         records or more columns

* `keys()` returns the columns in the result

=== Controlling the Columns in the Query

* You can pass a list of columns to be selected to the `select()` function

[source,python]
----
s = select([cookies.c.cookie_name, cookies.c.quantity])
----

=== Ordering

* The result of a `select()` function call accepts a `order_by()` method

[source,python]
----
s = select([cookies.c.cookie_name, cookies.c.quantity])
s.order_by(cookies.c.quantity)
----

* This is the same as

[source,python]
----
s = select(...).order_by(...)
----

* But having everything on a single line may make for a cumbersome code

* The author calls this chaining of statements a "generative fashion"
* It allows for query building by taking tiny steps
* This is quite useful because it allows for more complex builds such
  as having a statement being added to a query only if some condition
  is met in the "Python side"

* You can sort in descending order with `desc()`:

[source,python]
----
from sqlalchemy import desc
s = select(...)
s = s.order_by(desc(cookies.c.quantity))
----

* It is also possible to achieve the same with `cookies.c.quantity.desc()`, but it is a bit too verbose to me

=== Limiting

* As expected, is an additional function that can be applied to `select()`

[source,python]
----
from sqlalchemy import desc
s = select(...)
s = s.order_by(...)
s = s.limit(2)
----

=== Built-in

* SQL builtins such as `SUM()` and `COUNT()` may be found on `sqlalchemy.sql.func`
* They're applied around columns

[source,python]
----
from sqlalchemy.sql import func

s = select([func.sum(cookies.c.quantity)])
rp = connection.execute(s)
print(rp.scalar())
----

=== Filtering
=== ClauseElements
=== Operators
=== Boolean Operators
=== Conjuctions

== Updating Data
== Deleting Data
== Joins
== Aliases
== Grouping
== Chaining
== Raw Queries