= Essential SQLAlchemy Notes

This folder contains my notes and experiments while reading Essential SQLAlchemy,
by Jason Myers.

Please keep in mind that those notes are personal and publicized just in case
they're useful to someone, but I write them to myself. For example, I write
about things I find interesting or new, mostly ignore things I'm familiar with
and I don't go out of the way to explain some concepts that may be difficult
but I'm used with.

== Install

Using poetry, a `+poetry install+` will install SQLAlchemy, Psycopg2 driver,
ipython and some other dependencies. If you run into troubles with psycopg2,
`sudo aptitude install python3-dev libpq-dev` might help or look over
the official https://www.psycopg.org/docs/install.html#install-from-source[FAQ]

== Docker

The docker compose contains a small Postgres instance with a default user and password
of `+sqla+`.

You can run it with

[source,shell]
----
docker-compose up
----

Connect to it with

[source,python]
----
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://sqla:sqla@localhost:5433/sqla")
----